# -*- coding: utf-8 -*-
"""hhpanda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8AdqYEoGqxVQ2wLpPEFVzAn-MNe6aSH
"""

!sudo apt install openjdk-21-jdk
!wget "https://github.com/abdlhay/AbyssVideoDownloader/releases/download/v1.6.0/abyss-dl.jar"
from IPython.display import clear_output
clear_output()

# Chạy chương trình Java
!java -jar abyss-dl.jar "N5Up-LNIl" -o "tienvo134.mp4"

!zip -r /content/mp4_files.zip /content/*.mp4

!pip install tqdm

import requests
from tqdm import tqdm
from google.colab import files
import os

# Đường dẫn đến tệp zip trên Colab
file_path = '/content/mp4_files.zip'

# Lấy kích thước tệp
file_size = os.path.getsize(file_path)

# Tạo một yêu cầu tải xuống
with open(file_path, 'rb') as f:
    response = requests.get('https://example.com/download_link', stream=True)  # Thay 'https://example.com/download_link' bằng link tải xuống

    # Sử dụng tqdm để hiển thị thanh tiến trình
    with tqdm(total=file_size, unit='B', unit_scale=True, desc='Tải xuống') as pbar:
        for chunk in f:
            pbar.update(len(chunk))

# Sau khi tải xong, sử dụng files.download() để tải tệp về máy
files.download(file_path)
